### ISSUE TITLE
Criar página home do internet banking

### ISSUE THREAD

**Issue by samuelsp** [HeroesOfBank/gama-bank#17]

**Comment by samuelsp** [comment]
Criação da home page do projeto em mobile firts

**Comment by willrockies** [comment]
@samuelsp, estou colocando o required para o formularios e o validando o botão de acessar

**Comment by DouglasdeMoura** [comment]
Referenciando a PR #23

**Comment by samuelsp** [comment]
Adicionei as rotas para os componentes de AddUser e Login nos links internos da home.

**Comment by samuelsp** [comment]
Foi necessário criar novo componente AddUser e excluir o anterior da pasta user devido a conflito de nomes de componentes
