### ISSUE TITLE
Exibição das transações

### ISSUE THREAD

**Issue by jairtontf** [HeroesOfBank/gama-bank#9]
As trasações devem ser exibidas em formas de cards e devem conter o horário da transação (dd/MM/yyyy HH:mm:ss), o valor da transação e o destinatário.

Não é necessário os detalhes.

Quando a transação for **enviando dinheiro para outra conta**, colocar o valor em vermelho e colocar o sinal de subrtração. Ex,: -R$ 153,00

Caso **receba dinhero de outra pessoa** colocar o valor em verde com o sinal de adição. Ex. R$ 20,99

https://drive.google.com/file/d/14gjZoMNk1tBFHygct3EdiVSYqZz4xLzx/view?usp=sharing

**Comment by DouglasdeMoura** [comment]
Duplicado #12
